kind: pipeline
type: exec
name: notes

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - rb

steps:
  - name: build
    commands:
      - pwd
      - ls -l
      - cp . /home/cuihao/nginx/assets