kind: pipeline
type: exec
name: notes

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - rb

steps:
  - name: build
    commands:
      - mkdir -p /home/cuihao/nginx/assets/notes
      - cp -r . /home/cuihao/nginx/assets/notes